name: 'Post2BlueSky'
description: 'Send notifications to BlueSky social media for new content updates.'
author: 'Jeff Patton'

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  Message:
    description: 'The message to post, should either be plaintext, or bsky record, or bsky record containing a bsky repo'
    required: true
    type: string
  verbose:
    description: "A value of verbose will output additional information"
    required: false
    type: string
    default: 'None'
  bluesky_api_key:
    description: 'Your BlueSky App Password'
    required: true
  bluesky_identifier:
    description: 'Your BlueSky Identifier, something like user.bsky.social'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Send BlueSky Notification
      env:
          BLUESKY_API_KEY: ${{ inputs.bluesky_api_key }}
          BLUESKY_IDENTIFIER: ${{ inputs.bluesky_identifier }}
          VERBOSE: ${{ inputs.verbose }}
      run: |
        & $env:GITHUB_ACTION_PATH\\post2bsky.ps1 -Message ${{ inputs.Message }}
      shell: pwsh
