name: BlueSky Notification Workflow

on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      projectName:
        required: true
        type: string
    secrets:
      bluesky_api_key:
        required: true
      bluesky_identifier:
        required: true

jobs:
  notify_bluesky:
    runs-on: windows-latest
    name: Send notification to BlueSky
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send BlueSky Notification
        env:
          Password: ${{ secrets.bluesky_api_key }}
          Identifier: ${{ secrets.bluesky_identifier }}
          Source: ${{ inputs.source }}
          ProjectName: ${{ inputs.projectName }}
        run: |
          pwsh -File post2dbsky.ps1 -Source $Source -ProjectName $ProjectName -Identifier $Identifier -Password $Password
        shell: pwsh